// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrivingMapper.Data;

#nullable disable

namespace WardrivingMapper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WardrivingMapper.Data.RawData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("REAL");

                    b.Property<double>("AltitudeMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MAC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MfgrId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RCOIs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RSSI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SSID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RawData");
                });
#pragma warning restore 612, 618
        }
    }
}
